# Generated by Django 5.0.6 on 2024-06-25 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_comment_listing_user_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="id",
            field=models.SmallAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.SmallAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("No Category", "No Category"),
                    ("Fashion", "Fashion"),
                    ("Toys", "Toys"),
                    ("Electronics", "Electronics"),
                    ("Home", "Home"),
                    ("Other", "Other"),
                ],
                default="No Category",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.SmallAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://th.bing.com/th/id/OIP.mq4EytPnqsxmByNt_UmE8wHaHa?pid=ImgDet&w=203&h=203&c=7&dpr=1.3",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.SmallAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
